set -g base-index 1
set-option -g status-left-length 50
set-window-option -g mode-keys vi

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

set-option -g status-style bg=default,fg=colour223

set-option -g status-left "#[bg=colour248,fg=colour237] #S #[bg=default] #[bg=default]"
set-option -g status-right "#[bg=default] #[bg=default,fg=colour167] %Y-%m-%d | %H:%M #[bg=colour248,fg=colour237] #h "

set-window-option -g window-status-current-format "#[bg=colour248,fg=colour237] #I) #W #[bg=colour248,fg=colour237]"
set-window-option -g window-status-format "#[bg=default,fg=colour248] #I) #W #[bg=default,fg=colour248]"
