#!/usr/bin/env bash

# Chose a directory with fzf.
selected=$(find ~/my/projects/programs -mindepth 2 -maxdepth 2 -type d | fzf)
if [[ -z $selected ]]; then
    exit 0
fi

# Get the name of the selected directory.
selected_name=$(basename "$selected")

if [[ -z $TMUX ]]; then

    # Open selected in a new tmux session.
    tmux new-session -s $selected_name -c $selected
    exit 0
fi
