require('sidney.plugins.autopairs')
require('sidney.plugins.cmp')
require('sidney.plugins.lualine')
require('sidney.plugins.harpoon')
require('sidney.plugins.go')
require('sidney.plugins.telescope')
require('sidney.plugins.treesitter')
require('sidney.plugins.yanky')
require('sidney.plugins.luasnip')
require('sidney.plugins.web_dev_icons')

require('sidney.plugins.mason')
require('sidney.plugins.nullls')

require('sidney.plugins.dap_go')
require('sidney.plugins.dapui')
require('sidney.plugins.dap_virtual_text')
