require('sidney.plugins.autopairs')
require('sidney.plugins.cmp')
require('sidney.plugins.symbols_outline')
require('sidney.plugins.telescope')
require('sidney.plugins.treesitter')
require('sidney.plugins.lualine')
require('sidney.plugins.luasnip')
require('sidney.plugins.eyeliner')
