vim.cmd('colorscheme gruvbox')

-- Custom Gruvbox themed highlights.
vim.api.nvim_set_hl(0, 'HighlightYank', { ctermfg = 235, ctermbg = 214 })
vim.cmd([[ highlight! CursorLine ctermbg=NONE ]])
vim.cmd([[ highlight! CursorLineNr ctermbg=235 ctermfg=214 ]])
vim.cmd([[ highlight! TreesitterContext ctermbg=237 ]])
vim.cmd([[ highlight! TreesitterContextLineNumber ctermbg=237 ctermfg=214 ]])
vim.cmd([[ highlight! Pmenu ctermbg=234 ctermfg=223 ]])
vim.cmd([[ highlight! PmenuSel ctermbg=236 ctermfg=223 ]])
vim.cmd([[ highlight! PmenuSbar ctermbg=234 ]])
vim.cmd([[ highlight! PmenuThumb ctermbg=237 ]])
vim.cmd([[ highlight! TelescopePromptTitle ctermbg=NONE ctermfg=223 ]])
vim.cmd([[ highlight! TelescopePromptNormal ctermbg=236 ]])
vim.cmd([[ highlight! TelescopePromptBorder ctermbg=236 ]])
vim.cmd([[ highlight! TelescopePromptPrefix ctermfg=214 ]])
vim.cmd([[ highlight! TelescopeResultsTitle ctermbg=NONE ctermfg=234 ]])
vim.cmd([[ highlight! TelescopeResultsNormal ctermbg=234 ]])
vim.cmd([[ highlight! TelescopeResultsBorder ctermbg=234 ]])
vim.cmd([[ highlight! TelescopeSelection ctermbg=236 ]])
vim.cmd([[ highlight! TelescopePreviewTitle ctermbg=NONE ctermfg=223 ]])
vim.cmd([[ highlight! TelescopePreviewNormal ctermbg=234 ]])
vim.cmd([[ highlight! TelescopePreviewBorder ctermbg=234 ]])
