set-option -g status-style bg=colour237,fg=colour223

set-option -g status-left "#[bg=colour66,bold,fg=colour232] #S #[bg=default,fg=colour66] "
set-option -g status-right "   #[bg=default,fg=colour239]#[bg=colour239,fg=default] %Y-%m-%d / #[fg=colour167]%H:%M #[bg=colour239,fg=colour66]#[bg=colour66,bold,fg=colour232] #h "

set-window-option -g window-status-current-format "#[fg=colour66]#[bg=colour66,bold,fg=colour232] #I:#W #[bg=default,fg=colour66]"
set-window-option -g window-status-format "#[fg=colour239]#[bg=colour239,fg=default] #I:#W #[bg=default,fg=colour239]"
