set -g pane-border-style fg=#3C4043
set -g pane-active-border-style "bg=default fg=#9AA0A6"

set-option -g status-style bg=default,fg=#ffffff

set-option -g status-left "#[bold,fg=#87FFC5]  #S         "
set-option -g status-right "#[fg=#f28b82] %H:%M#[fg=#87FFC5,bold]        #h "

set-window-option -g window-status-current-format "#[bold,fg=#AECBFA] #I:#W  "
set-window-option -g window-status-format "  #I:#W   "
