set-option -g status-style bg=default,fg=#ffffff

set-option -g status-left "#[bold,fg=colour10]  #S     "
set-option -g status-right "#[fg=colour1]%H:%M#[fg=colour10,bold]     #h "

set-window-option -g window-status-current-format "#[bold,fg=colour4]#I:#W "
set-window-option -g window-status-format "#[]#I:#W "
