set-option -g status-left-length 50
set-window-option -g mode-keys vi
set -g default-terminal "screen-256color"

# Pane navigation.
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Window swapping.
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

source-file ~/.config/tmux/tmux_minimal-bar.conf
